# server port
server:
  port: 8081

# postgresql connect
spring:
  datasource:
    url: jdbc:postgresql://localhost:8036/db_friendsofclubs
    username: friendsofclubs
    password: friendsofclubs
    driver-class: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# mysql connect
# spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/jwt_security
#    username: root
#    password:
#    driver-class: com.mysql.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
